name: hmcamera
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4 
  gallery_saver: ^2.3.0
  path_provider: ^2.0.11
  archive: ^3.6.1
  crypto: ^3.0.3
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.4
  flutter_background_service_ios: ^5.0.2
  flutter_background_service_platform_interface: ^5.1.1
  flutter_lints: ^4.0.0
  flutter_web_plugins:
    sdk: flutter
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+4
  permission_handler: ^10.2.0
  http: ^0.13.4
  image: ^3.0.1
  js: ^0.6.3
  location: ^7.0.0
  location_platform_interface: ^5.0.0
  location_web: ^5.0.3
  mime: ^1.0.5
  pedometer: ^4.0.2
  petitparser: ^6.0.2
  platform: ^3.1.5
  plugin_platform_interface: ^2.1.8
  share_plus: ^10.0.0
  typed_data: ^1.3.2
  web: ^0.5.1
  xml: ^6.5.0
  intl: ^0.17.0
  exif: ^2.1.1
  provider: ^6.0.3
  flutter_compass: ^0.7.0
  device_info_plus: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0

dependency_overrides:
  vm_service: 14.2.1

flutter:
  uses-material-design: true
